version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: 8n8-mongodb
    restart: unless-stopped
    command:
      [
        "bash",
        "-lc",
        "chmod 600 /data/configdb/keyfile && exec mongod --replSet rs0 --bind_ip_all --keyFile /data/configdb/keyfile",
      ]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: 8n8
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/mongo-init-replica.js:/docker-entrypoint-initdb.d/mongo-init-replica.js:ro
      - ./docker/mongo-keyfile:/data/configdb/keyfile
    networks:
      - 8n8-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: 8n8-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 8n8-network

volumes:
  mongodb_data:
    driver: local

networks:
  8n8-network:
    driver: bridge
